// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Lugares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Posicao = "A0",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Posicao = "A1",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Posicao = "A2",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Posicao = "A3",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Posicao = "A4",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Posicao = "A5",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Posicao = "A6",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Posicao = "A7",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Posicao = "A8",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Posicao = "A9",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Posicao = "B0",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Posicao = "B1",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Posicao = "B2",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Posicao = "B3",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Posicao = "B4",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Posicao = "B5",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Posicao = "B6",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Posicao = "B7",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            Posicao = "B8",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Posicao = "B9",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Posicao = "C0",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            Posicao = "C1",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            Posicao = "C2",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            Posicao = "C3",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            Posicao = "C4",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            Posicao = "C5",
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            Posicao = "C6",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            Posicao = "C7",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            Posicao = "C8",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            Posicao = "C9",
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            Posicao = "D0",
                            Status = 1
                        },
                        new
                        {
                            Id = 32,
                            Posicao = "D1",
                            Status = 1
                        },
                        new
                        {
                            Id = 33,
                            Posicao = "D2",
                            Status = 1
                        },
                        new
                        {
                            Id = 34,
                            Posicao = "D3",
                            Status = 1
                        },
                        new
                        {
                            Id = 35,
                            Posicao = "D4",
                            Status = 1
                        },
                        new
                        {
                            Id = 36,
                            Posicao = "D5",
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            Posicao = "D6",
                            Status = 1
                        },
                        new
                        {
                            Id = 38,
                            Posicao = "D7",
                            Status = 1
                        },
                        new
                        {
                            Id = 39,
                            Posicao = "D8",
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            Posicao = "D9",
                            Status = 1
                        },
                        new
                        {
                            Id = 41,
                            Posicao = "E0",
                            Status = 1
                        },
                        new
                        {
                            Id = 42,
                            Posicao = "E1",
                            Status = 1
                        },
                        new
                        {
                            Id = 43,
                            Posicao = "E2",
                            Status = 1
                        },
                        new
                        {
                            Id = 44,
                            Posicao = "E3",
                            Status = 1
                        },
                        new
                        {
                            Id = 45,
                            Posicao = "E4",
                            Status = 1
                        },
                        new
                        {
                            Id = 46,
                            Posicao = "E5",
                            Status = 1
                        },
                        new
                        {
                            Id = 47,
                            Posicao = "E6",
                            Status = 1
                        },
                        new
                        {
                            Id = 48,
                            Posicao = "E7",
                            Status = 1
                        },
                        new
                        {
                            Id = 49,
                            Posicao = "E8",
                            Status = 1
                        },
                        new
                        {
                            Id = 50,
                            Posicao = "E9",
                            Status = 1
                        },
                        new
                        {
                            Id = 51,
                            Posicao = "F0",
                            Status = 1
                        },
                        new
                        {
                            Id = 52,
                            Posicao = "F1",
                            Status = 1
                        },
                        new
                        {
                            Id = 53,
                            Posicao = "F2",
                            Status = 1
                        },
                        new
                        {
                            Id = 54,
                            Posicao = "F3",
                            Status = 1
                        },
                        new
                        {
                            Id = 55,
                            Posicao = "F4",
                            Status = 1
                        },
                        new
                        {
                            Id = 56,
                            Posicao = "F5",
                            Status = 1
                        },
                        new
                        {
                            Id = 57,
                            Posicao = "F6",
                            Status = 1
                        },
                        new
                        {
                            Id = 58,
                            Posicao = "F7",
                            Status = 1
                        },
                        new
                        {
                            Id = 59,
                            Posicao = "F8",
                            Status = 1
                        },
                        new
                        {
                            Id = 60,
                            Posicao = "F9",
                            Status = 1
                        },
                        new
                        {
                            Id = 61,
                            Posicao = "G0",
                            Status = 1
                        },
                        new
                        {
                            Id = 62,
                            Posicao = "G1",
                            Status = 1
                        },
                        new
                        {
                            Id = 63,
                            Posicao = "G2",
                            Status = 1
                        },
                        new
                        {
                            Id = 64,
                            Posicao = "G3",
                            Status = 1
                        },
                        new
                        {
                            Id = 65,
                            Posicao = "G4",
                            Status = 1
                        },
                        new
                        {
                            Id = 66,
                            Posicao = "G5",
                            Status = 1
                        },
                        new
                        {
                            Id = 67,
                            Posicao = "G6",
                            Status = 1
                        },
                        new
                        {
                            Id = 68,
                            Posicao = "G7",
                            Status = 1
                        },
                        new
                        {
                            Id = 69,
                            Posicao = "G8",
                            Status = 1
                        },
                        new
                        {
                            Id = 70,
                            Posicao = "G9",
                            Status = 1
                        },
                        new
                        {
                            Id = 71,
                            Posicao = "H0",
                            Status = 1
                        },
                        new
                        {
                            Id = 72,
                            Posicao = "H1",
                            Status = 1
                        },
                        new
                        {
                            Id = 73,
                            Posicao = "H2",
                            Status = 1
                        },
                        new
                        {
                            Id = 74,
                            Posicao = "H3",
                            Status = 1
                        },
                        new
                        {
                            Id = 75,
                            Posicao = "H4",
                            Status = 1
                        },
                        new
                        {
                            Id = 76,
                            Posicao = "H5",
                            Status = 1
                        },
                        new
                        {
                            Id = 77,
                            Posicao = "H6",
                            Status = 1
                        },
                        new
                        {
                            Id = 78,
                            Posicao = "H7",
                            Status = 1
                        },
                        new
                        {
                            Id = 79,
                            Posicao = "H8",
                            Status = 1
                        },
                        new
                        {
                            Id = 80,
                            Posicao = "H9",
                            Status = 1
                        },
                        new
                        {
                            Id = 81,
                            Posicao = "I0",
                            Status = 1
                        },
                        new
                        {
                            Id = 82,
                            Posicao = "I1",
                            Status = 1
                        },
                        new
                        {
                            Id = 83,
                            Posicao = "I2",
                            Status = 1
                        },
                        new
                        {
                            Id = 84,
                            Posicao = "I3",
                            Status = 1
                        },
                        new
                        {
                            Id = 85,
                            Posicao = "I4",
                            Status = 1
                        },
                        new
                        {
                            Id = 86,
                            Posicao = "I5",
                            Status = 1
                        },
                        new
                        {
                            Id = 87,
                            Posicao = "I6",
                            Status = 1
                        },
                        new
                        {
                            Id = 88,
                            Posicao = "I7",
                            Status = 1
                        },
                        new
                        {
                            Id = 89,
                            Posicao = "I8",
                            Status = 1
                        },
                        new
                        {
                            Id = 90,
                            Posicao = "I9",
                            Status = 1
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LugarId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("backend.Domain.Entities.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
